version: '2'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx_proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "/etc/nginx/vhost.d"
            - ./conf.d/my_conf.conf:/etc/nginx/conf.d/my_conf.conf
            - "/usr/share/nginx/html"
            - "/var/run/docker.sock:/tmp/docker.sock:ro"
            - ./certs:/etc/nginx/certs
    letsencrypt-nginx-proxy-companion:
        image: jrcs/letsencrypt-nginx-proxy-companion
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        volumes_from:
            - "nginx-proxy"
